# Generated by Django 4.2.6 on 2023-11-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('license', models.CharField(max_length=1)),
                ('image', models.ImageField(default='uploads/images/profile.jpg', upload_to='uploads/media')),
            ],
        ),
    ]
