# Generated by Django 4.2.6 on 2023-11-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='license',
            new_name='licence',
        ),
    ]
