# Generated by Django 4.2.6 on 2023-11-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text1',
            field=models.CharField(max_length=30),
        ),
    ]
